Add libxml2-utils dependency for xmllint
/bin/sh /tmp/buildd/postgresql-9.5-9.5~~devel~20141115.1540/build/../config/missing xmllint --noout --valid postgres.xml
***
ERROR: `xmllint' is missing on your system.
***
Makefile:85: recipe for target 'man-stamp' failed